// ---------------------------------------------------------------------------
// TypeScript Constants Generator
//
// Produces a TS source file exporting:
//   - TOKEN_NAMES: a const object mapping camelCase keys to CSS variable names
//   - cssVar(): a helper that wraps a token name in var(--...)
// ---------------------------------------------------------------------------

import type { TokenRegistry } from '../types.js';
import { getAllTokens } from '../definitions/index.js';

/**
 * Convert a token name like `st-color-bg-surface-base` to camelCase:
 * `stColorBgSurfaceBase`.
 */
function toCamelCase(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

export function generateTypeScriptConstants(registry?: TokenRegistry): string {
  const reg = registry ?? getAllTokens();
  const lines: string[] = [];

  lines.push('// Auto-generated by @staple-css/tokens — do not edit by hand.');
  lines.push('');
  lines.push('/**');
  lines.push(' * Wraps a token name in a CSS `var()` function call.');
  lines.push(' *');
  lines.push(' * @example');
  lines.push(' * ```ts');
  lines.push(' * cssVar("st-color-bg-surface-base")');
  lines.push(' * // => "var(--st-color-bg-surface-base)"');
  lines.push(' * ```');
  lines.push(' */');
  lines.push('export function cssVar(name: string): string {');
  lines.push('  return `var(--${name})`;');
  lines.push('}');
  lines.push('');

  lines.push('/** All token names as typed constants. */');
  lines.push('export const TOKEN_NAMES = {');

  // Color tokens
  for (const t of reg.color) {
    lines.push(`  ${toCamelCase(t.name)}: '${t.name}',`);
  }

  // Scale tokens
  const scaleCategories: { name: string; value: string; description: string }[][] = [
    reg.space,
    reg.type,
    reg.elevation,
    reg.border,
    reg.motion,
    reg.layout,
    reg.flex,
    reg.grid,
  ];

  for (const tokens of scaleCategories) {
    for (const t of tokens) {
      lines.push(`  ${toCamelCase(t.name)}: '${t.name}',`);
    }
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type TokenName = (typeof TOKEN_NAMES)[keyof typeof TOKEN_NAMES];');

  return lines.join('\n');
}
